### ISSUE TITLE
Corregir diseño de detalle de post

### ISSUE THREAD

**Issue by earias08** [facund1n/3i-show#56]
### Proceso
---
Ingreso a la pagina de detalle de un post

### Resultado esperado
---
Visualizar la información del post

### Resultado actual
---
Si la imagen cargada es erronea no se visualiza, los post con muchos caracteres en titulo y descripcion rompen el diseño

### Captura

![image](https://user-images.githubusercontent.com/18445151/221302901-7caaa991-46a9-49d8-a8bb-b7518f892f78.png)

**Comment by emiarias** [comment]
Cuando una palabra es demasiado larga y sale del contenedor, sugiero utilizar `text-overflow: ellipsis;`
